#!/bin/sh

set -eu

if ! gh help > /dev/null; then
  echo "gh is required."
  echo "Please see: https://github.com/cli/cli"
  exit 1
fi

YEAR=""
MONTH=""
REPO=""

for i in "$@"; do
  case $i in
      --year=*)
      YEAR="${i#*=}"
      shift
      ;;
      --month=*)
      MONTH="${i#*=}"
      shift
      ;;
      --repo=*)
      REPO="${i#*=}"
      shift
      ;;
  esac
done

if [ -z "$YEAR" ] || [ -z "$MONTH" ] || [ -z "$REPO" ]; then
    echo "Usage: $0 --year=YYYY --month=MM --repo=orgName/repoName"
    exit 1
fi

LAST_DAY=$(cal $MONTH $YEAR | awk 'NF {DAYS = $NF}; END {print DAYS}')
SINCE="$YEAR-$MONTH-01"
UNTIL="$YEAR-$MONTH-$LAST_DAY"

prs=$(gh pr list --repo "$REPO" --state all --search "created:>$SINCE closed:<$UNTIL" --json number,title,author --limit 300)

echo "$prs" | jq '[group_by(.author.login)[] | {author: .[0].author.login, count: length}]'
